version: 0.2
phases:
  build:
    commands:
      - export BUCKET=samapp-sam-ks-411045
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  files:
    - outputtemplate.yaml
